std_msgs/Header header
float32[] receiver_distance
float32[] receiver_nsd
float32[] receiver_rssi
float32[] receiver_valid
float32 std	# Current accoustic position accuracy (meter)
float32 x	# Current accoustic x position relative to master electronics (meter)
float32 y	# Current accoustic y position relative to master electronics (meter)
float32 z	# Current accoustic z position (depth) relative to master electronics (meter)
