std_msgs/Header header

int16 cog		# Course over ground (degrees). -1 means no data.
float32 hdop		# Horizontal dilution of precision. -1 means no data.
float32 lat		# Current Latitude
float32 lon		# Current Longitude
int16 numsats		# Number of satellites. -1 means no data.
int16 orientation	# Current orientation/compass heading (degrees). -1 means no data.
float32 sog		# Speed over ground (km/h). -1 means no data.
