#!/usr/bin/env python3
import rospy
from bluerov2_guidance import LineOfSight


if __name__ == "__main__":
    rospy.init_node("guidance")#, log_level=rospy.DEBUG)
    try:
        guidance = LineOfSight()
        rospy.spin()
    except rospy.ROSInterruptException:
        pass
